rsnapshot:
  container_name: rsnapshot
  image: gafonso21/docker-rsnapshot
  volumes:
    - redmine-mikroways-files:/tmp
    - rsnapshot-keys:/root/.ssh
    - rsnapshot:/etc
    #- rsnapshot-config:/etc/
    #- rsnapshot-otroconfig:/usr/bin/rsnapshot.d
  environment:
    BACKUP_DIRECTORIES: 'root@104.131.23.223:/tmp/ ./README.md'
