rsnapshot:
  container_name: rsnapshot
  image: gafonso21/docker-rsnapshot
  volumes:
    - redmine-mikroways-files:/tmp
    - rsnapshot-keys:/root/.ssh
    - rsnapshot:/etc
    - buckppp:/snapshots
    #- rsnapshot-config:/etc/
    #- rsnapshot-otroconfig:/usr/bin/rsnapshot.d
  environment:
    BACKUP_DIRECTORIES: '/tmp root@104.131.23.223:/tmp/'
