rsnapshot:
  container_name: rsnapshot
  #image: gafonso21/docker-rsnapshot
  build: .
  volumes:
    - redmine-mikroways-files:/opt/applications/redmine #volumen con los datos que se deseen copiar
    - rsnapshot-keys:/root/.ssh #Volumen con las claves ssh
    - rsnapshots-bkp:/var/rsnapshot #Volumen que contiene los bkps
  environment:
    BACKUP_DIRECTORIES: |
                 /docker-entrypoint.sh	./
  #command: ["rsnapshot", "hourly"]
  #command: ["rsnapshot", "daily"]
  #command: ["rsnapshot", "weekly"]
